### ISSUE TITLE
HEROKU – migration heroku-18

### ISSUE THREAD

**Issue by Hiswe** [Badsender/mosaico#10]
NightmareJS prevents migrating from deprecated stack `cedar-14` to `heroku-18`
Migrating to heroku-16 will allow us:

- don't break the application on April 2019 (end of cedar-14's life)
- to migrate to Node 10

Steps:

- [x] replace nightmare by [puppeteer](https://pptr.dev/)
- [x] make a new heroku dev-env with heroku-18
- [x] deploy stage
  - [x] change build-pack to:
    ```
    https://github.com/jontewks/puppeteer-heroku-buildpack.git
    heroku/nodejs
    ```
  - [x] change stack to `heroku-18`
  - [x] session affinity
  - [x] deploy code
- [x] deploy prod
  - [x] change build-pack to:
    ```
    https://github.com/jontewks/puppeteer-heroku-buildpack.git
    heroku/nodejs
    ```
  - [x] change stack to `heroku-18`
  - [x] session affinity
    ```
    heroku features:enable http-session-affinity -a badsender    
    ```
  - [x] deploy code

ressources:

- [puppeteer-heroku-buildpack ](https://github.com/jontewks/puppeteer-heroku-buildpack)
- [cedar-14 documentation](https://devcenter.heroku.com/articles/cedar-14-stack)

**Comment by Hiswe** [comment]
@Badsender Il faudrait tester le dev, surtout la fonction de génération d'images

**Comment by Badsender** [comment]
Tout semble fonctionner nickel! GO pour le stage

**Comment by Hiswe** [comment]
@Badsender en stage.

**Comment by Badsender** [comment]
Stage nickel au niveau génération d'image, et fonctionnement idem.
GO prod

**Comment by Hiswe** [comment]
@Badsender en prod
J'ai testé la partie “preview generation” et ça fonctionne.
Je te laisse valider plus en détail.
