### ISSUE TITLE
Nouvelle fonctionnalité: crop d'images

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#11]
- [x] resize d'image dans l'upload de la galerie
- [x] dans le template on garde le comportement actuel 

---

Hello Yannick,

Suite à des demandes client, nous sommes en train d'envisager une nouvelle fonctionnalité dans le builder, l'édition (rudimentaire) d'images.

Au chargement d'une image dans le builder, on souhaite pouvoir:
- redécouper une image (façon crop dans Photoshop) manuellement ou en fixant les dimensions. Exemple: l'outil d'édition de photo de profil de LinkedIn (sans les modules d'options de couleurs)

Pourrais-tu me donner un devis par rapport à ça?

On peut évidemment se faire un call si question.

**Comment by Badsender** [comment]
Mmm, non, ce ne serait pas l'idée. 
Ce serait plutôt une étape avant l'insertion dans le template:
- On charge l'image via l'outil qui permet le crop
- L'image est chargée soit dans la gallerie, soit dans le template (avec le fonctionnement actuel du chargement des images)

**Comment by Hiswe** [comment]
@Badsender Il vaudrait mieux effectivement qu'on s'appelle pour en parler :)

**Comment by Hiswe** [comment]
@Badsender en stage (en attendant que l'on puisse reprendre le process normal #13 )

**Comment by Badsender** [comment]
C'est good!
GO pour la prod

**Comment by Hiswe** [comment]
@Badsender comme je n'avais pas 2 servers pour vous donner à tester le crop et le DL+CDN j'ai tout mergé.
Il faudra attendre que le DL+CDN soit valider pour la MeP

**Comment by Badsender** [comment]
Ok. J'attends le GO du client pour CDN, après on pourra pousser en prod!

**Comment by Badsender** [comment]
GO pour la prod!

**Comment by Hiswe** [comment]
@Badsender done
