### ISSUE TITLE
ZIP EXPORT – can be configured to point out a CDN

### ISSUE THREAD

**Issue by Hiswe** [Badsender/mosaico#22]
see quotation

### admin

- [x] ajout d'une switch pour activer l'option sur une page de société
- [x] switch activé => montrer un champ de saisi de l'end-point CDN

### DL

téléchargement d'un fichier unique :

- [x] fichier actuel + images gardées
- [x] ajout d'un second fichier préfixé `CDN-` avec les images pointant sur celui-ci

**Comment by Hiswe** [comment]
@Badsender pour les images à rerouter sur le CDN, ce sont bien uniquement celles présente sur le site du builder ?

example : 

```
  'http://test.badsender.com/emailBuilder/template_01/logo.png',
  'http://cdn.comapny.com/email_builder_template/invest/facebook.png',
  'http://localhost:3000/placeholder/262x350.png',
  'http://localhost:3000/resize/220xnull/5ae9bb7f8bd38d0023aa5827-38c3a8e0c18936a15ef54ea81648d5a9.jpeg',
```

sur ces 4 images présentes sur le mailing seules les 2 dernières seraient à changer pour pointer sur le CDN configuré ?

**Comment by Badsender** [comment]
Non, il faut toutes les changer, car à l'export du zip, tout passe en:
images/mon_image.jpg

Que ce soit des images déjà présentes, comme:
'http://test.badsender.com/emailBuilder/template_01/logo.png'
ou des images chargées par l'utilisateur

**Comment by Hiswe** [comment]
@Badsender en stage (en attendant que l'on puisse reprendre le process normal #13 )

**Comment by Badsender** [comment]
Hello Yannick,

Quelques points à modifier:
- Le chemin des images doit pouvoir comporter le nom de l'email.
- Est-ce que ce serait compliqué, une fois le switch activé, de proposer lors du téléchargement une option: Standard / CDN ?
- Si l'idée ci-dessus est trop compliquée, serait-il possible de mettre le switch au niveau du template et non de la société?

**Comment by Hiswe** [comment]
@Badsender 

- le chemin comporte déjà le nom de l'email. Juste que je fais en sorte d'en faire une valide.
  si le CDN est `http://cdn.client.com`
  que le nom de l'email est `test download`
  le path complet sera `http://cdn.client.com/test-download`
- pour le switch, j'ai mis les 2 fichiers HTML dans le zip. Celui préfixé par `CDN_` étant le bon. L'autre est en path relatif comme avant.
- cela évite d'encombrer l'UX

**Comment by Hiswe** [comment]
@Badsender Après si pour vous c'est obligatoire d'avoir juste le contenu nécessaire dans le zip, on peut faire 2 boutons oui :)

**Comment by Badsender** [comment]
Hello @Hiswe ,

Je confirme la demande client. L'idée serait d'avoir au clic ou au survol du bouton télécharger, une dropdown proposant les 2 options de téléchargement.
Le client demande également de pouvoir personnaliser le nom de ce téléchargement particulier. CDN n'étant pas clair pour leurs marketeers…
Serait-il possible de l'appeler ICOU ? Dans l'idéal, le mieux serait de pouvoir personnaliser le nom afin de pouvoir réutiliser ça pour d'autres clients, mais si c'et embêtant ce n'est pas prioritaire puisque pour le moment, Beobank est le seul client à demander ça

**Comment by Hiswe** [comment]
@Badsender mis à jour sur le stage

Le libellé est configurable dans le backoffice.
Il ne sera juste pas internationalisé 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/96121/58380298-bdb0dd80-7faf-11e9-996e-9154a98a7e0e.png">

**Comment by Badsender** [comment]
GO pour la prod!

**Comment by Hiswe** [comment]
@Badsender done
