### ISSUE TITLE
Non-encodage du code Selligent dans le builder

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#24]
Hello,

Il faudrait mettre en place u système équivalent aux balises AdobeCampaign (tout ce qui se trouve entre **<%** et **%>**  ne doit pas être encodé) pour les balises Selligent
Les balises Selligent sont entre tilde et ressemblent donc à ça:
\~code_selligent\~

Ces balises peuvent se retrouver dans:
- Du texte
- une URL de lien
- une URL d'image
- des balises HTML

exemples :

```
~(FORMATDATETIME(GETDATE(), '%d%m%Y'))~
```

Pour le moment, ça devient:

```
~(FORMATDATETIME(GETDATE(),%20%27%d%m%Y%27))~ 
```

**Comment by Hiswe** [comment]
@Badsender Il me faudrait sans doute un template avec le tag qui ne fonctionne pas.
Là comme ça je n'arrive pas à reproduire.

**Comment by Badsender** [comment]
@Hiswe Tu peux trouver un exemple dans le template "lequipe". Dans ce template, tu prends le bloc "doubleCoverBlock"

Le lien mis sur la première image de ce bloc correspond très exactement au problème donné dans l'exemple ci-dessus.

Ce template est disponible en stage et en prod

**Comment by Hiswe** [comment]
Ok de ce que je vois ça ne se produit que dans les `src` d'images ou les `href` de liens.

**Comment by Hiswe** [comment]
@Badsender Ça devrait être corrigé.

Je te laisse tester sur cet exemple.

https://mosaico-badsender-test.herokuapp.com/editor/5c9bd1c4b604b200122ca067

Aussi c'est la première version qui utilise le nouveau système de build (qui nous permettra de fluidifier les deploys). Il faudrait donc faire une petit tour sur toute l'application voir si tout va bien ^^
Et sur ce sujet je n'ai toujours pas les droits pour ajouter une application en dev pour le `pipeline` badsender

**Comment by Badsender** [comment]
Pour le code Selligent, c'est OK!

Pour le reste, j'ai parcouru l'appli et rien ne me semble cassé ;-)

**Comment by Hiswe** [comment]
@Badsender sur le stage

**Comment by Badsender** [comment]
@Hiswe  C'est tout bon. GO pour la prod!
