### ISSUE TITLE
Permission denied to access property "nodeType"

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#26]
Hello,

Voici le problème:
J'ai un template dans lequel il y a un paramètre "articleNumber" qui peut aller de 1 à 3 défini comme suit:
`[articleNumber {label: Articles; widget: integer; max: 3;}](url)`

Dans le template, j'ai 3 articles avec, sur chacun d'eux, une conditon d'affichage de type: `data-ko-display="articleNumber > 0`
`data-ko-display="articleNumber > 1`
`data-ko-display="articleNumber > 2`

L'affichage et l'édition fonctionnent bien tant que les 3 articles sont affichés par défaut. Si le articleNumber commence en dessous de 3 et qu'on l'augmente, les articles cachés vont alors s'afficher correctement, mais les textes ne seront pas éditables (les images et autres options restent bien éditables par contre)

Une erreur est envoyée par la console:
`Error: Permission denied to access property "nodeType"[Learn More] badsender-lib-editor.js:49457:4`

Tu peux tester ça sur le dev:
Compte **Test,** template **Test**

**Comment by Hiswe** [comment]
@Badsender Je n'ai pas réussit à reproduire.

Voilà les tests que j'ai fait :

### test 1

- utiliser le template tel quel
- modifier le nombre de blocs à `1` 
- éditer
- rajouter un bloc puis éditer (2 fois, sans problèmes)

### test 2

- télécharger le code HTML du template
- changer la ligne 191 à `articlesBlock {label: Articles; properties: articleNumber=1; theme: contentTheme;}`
- créer un nouveau template à partir ça
- créer un nouveau mailing
  - éditer le bloc `1`
  - rajouter un bloc puis éditer (2 fois, sans problèmes)
  - jouer avec les toggles

J'ai dans la console des erreurs lié aud drag & drop (`Unable to preventDefault inside passive event listener invocation`) mais l'appli fait ce qui est attendu d'elle.

Si tu pouvais me donner un step-by-step pour reproduire ça serait super !

**Comment by Badsender** [comment]
La procédure qu tu décris est celle que je mets en place.
Pour précision, au cas où:
- Par défaut, le nombre d'articles est de 3
- Tous les articles sont éditables
- Réduire le nombre d'articles à 2 ; les articles restant sont encore éditables
- Augmenter le nombre d'article à 3 (c'est à cette étape que l'ereur apparaît dans la console)
- Les articles 1 et 2 restent éditables, mais le 3e article, qui vient d'être ré-affiché, ne l'est plus.

**Comment by Badsender** [comment]
Je viens de voir que le problème ne se pose pas avec Chrome.
Le problème se pose avec Firefox (et peut-être d'autres navigateurs)

**Comment by Hiswe** [comment]
@Badsender J'ai testé une solution qui semble fonctionner même si je ne comprends pas trop pourquoi.

J'ai remplacé

```
articleNumber {label: Articles; widget: integer; max: 3;}
```

par

```
articleNumber {label: Articles; widget: select; options: 1|2|3;}
```

et au changement de chiffre ça fonctionne…

**Comment by Hiswe** [comment]
@Badsender J'ai essayé de voir d'où ça peut vraiment venir mais sans succès.

**Comment by Hiswe** [comment]
workaround accepté par Skype le jeudi 4 avril 2019
