### ISSUE TITLE
Aperçu mobile + classes spécifiques

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#32]
Hello Yannick,

Nous souhaiterions développer du contenu spécifique pour mobile (ou pour desktop) dans les emails sorti par le builder. 

L'idéal serait de pouvoir éditer l'email en choisissant un aperçu desktop (comme celui existant actuellement) ou un aperçu mobile (qui ferait 320px de large). L'aperçu mobile existe déjà, mais ne permet pas l'édition.
Ce serait, je pense, la solution idéale puisqu'elle permettrait de switcher entre les 2 rendus. 

Pourrais-tu me dire dans mesure ce projet serait envisageable? Ou bien si tu vois d'autres solutions?

Dispo sur Skype pour en discuter si tu veux

**Comment by Hiswe** [comment]
@Badsender je viens de regarder.

L'aperçu est fait dans une iframe, ce qui permets un rendu véritablement à la bonne taille, mais ne permettra jamais l'édition.

On peut s'arranger avec un système de classe et une config de breakpoint pour simuler ça dans la partie éditeur

**Comment by Hiswe** [comment]
@Badsender serait-il de me fournir un template de test ?
Je vais déjà commencer à mettre la preview iframe disponible sur tout types d'écrans

**Comment by Hiswe** [comment]
@Badsender il faudra vraiment qu'on ait un template de test :)

https://github.com/marcj/css-element-queries
https://github.com/eqcss/eqcss

**Comment by Badsender** [comment]
Hello Yannick,

Le template est enfin dispo! Tu peux le trouver dans:
https://badsender-test.herokuapp.com
Company: Tech test
Template: Mobile test

**Comment by Hiswe** [comment]
faire le test avec 2 balises style et un parse de CSS

**Comment by Badsender** [comment]
Hello Yannick,

J'ai pensé à une autre solution, probablement plus simple. Je vais voir pour te décrire ça et te faire un template démo cette semaine!

**Comment by Badsender** [comment]
Hello Yannick,

Bon, nous avons 3 cas de figure:
- Bloc visible sur desktop et sur mobile
- Bloc visible sur desktop uniquement
- Bloc visible sur mobile uniquement

1) Pour le premier cas de figure, c'est facile, c'est déjà le cas actuellement
2) C'est relativement simple aussi, puisqu'il suffit de mettre une classe dans les media queries qui va cacher le bloc en question. L'édition se faisant sur affichage desktop, ça ne pose pas de soucis
3) Pour afficher un bloc sur mobile uniquement, il faut appliquer des propriétés CSS dessus, en inline et dans la balise style, ce qui va cacher le bloc en desktop (et empêchera donc son édition dans le builder). La classe utilisée dans la balise style standard est:
```
.visibility_mobile {
	display:none !important;
	mso-hide:all !important; /* hide elements in Outlook 2007-2013 */
	visibility:hidden !important;
	max-height:0 !important;
	font-size:0 !important;
	line-height:0 !important;
	padding:0 !important;
}
```
Et la classe utilisée dans la partie media queries est:
```
.visibility_mobile {
	 max-height:none !important;
	 font-size:1px !important;
	 display:block !important;
	 overflow:visible !important;
	 visibility:visible !important;
	 line-height:1px !important;
	 float:none !important;
}
```

Comme tu peux le constater, la classe déclarée dans les media queries "contrecarre" la classe générale.

L'idée serait donc d'avoir, pendant qu'on édite dans le builder, toujours la même classe dans la partie media queries, et ceci dans la partie desktop:
.visibility_mobile {
	display:none !important;
	mso-hide:all !important; /* hide elements in Outlook 2007-2013 */
	visibility:hidden !important;
	max-height:0 !important;
	font-size:0 !important;
	line-height:0 !important;
	padding:0 !important;
}

.visibility_mobile {
	 max-height:none !important;
	 font-size:1px !important;
	 display:block !important;
	 overflow:visible !important;
	 visibility:visible !important;
	 line-height:1px !important;
	 float:none !important;
}
```
De cette manière, le bloc s'affichera en desktop pour l'édition puisque la classe est directement contrecarrée. Par contre, lors de l'export de l'email, il faudrait supprimer, dans la balise style, cette deuxième classe (et évidemment, la laisser tranquille dans la partie media queries). Il faudrait également faire de même lorsque l'on appuie sur le bouton qui permet d'obtenir le rendu.

Tu trouveras un exemple au même endroit:
https://badsender-test.herokuapp.com
Company: Tech test
Template: Mobile test

**Comment by Hiswe** [comment]
@Badsender J'ai dû rajouter une class pour masquer sur mobile… `visibility_desktop_only`

https://badsender-test.herokuapp.com/editor/5d73f2f19b140f001288b3e9

**Comment by Hiswe** [comment]
@Badsender vu que tout est dans la même release, j'ai mis ça en stage.
On pourra continuer à l'améliorer par la suite

**Comment by Hiswe** [comment]
@Badsender comme pour précédemment c'est en production.
Il faudra créer un nouveau ticket pour les améliorations
