### ISSUE TITLE
Update du crop d'image

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#33]
Hello Yannick,

Une demande d'update déjà pour le croppeur d'image:
Serait-il possible d'avoir les valeurs en pixels du cadre de crop? Cela permettrait aux utilisateurs d'être certains d'avoir des images carrées par exemple pour éviter d'avoir des rendus "à peu près" de type 300x302

**Comment by Hiswe** [comment]
@Badsender Ça devrait être possible (voir [cropperjs](https://fengyuanchen.github.io/cropperjs/))
Après pour le rendu “à peu près” c'est quand même automatiquement corrigé au moment de l'upload de l'image

**Comment by Badsender** [comment]
Dans tous les cas, le mieux est de permettre aux utilisateurs de voir les dimensions de leur crop, de manière à garder les dimensions qu'ils souhaitent.

PS: Comme ça ne semble pas prendre trop de temps, je l'ai passé en prio 1.

**Comment by Hiswe** [comment]
@Badsender en dev !

**Comment by Badsender** [comment]
C'est TOP!

GO pour le stage :-)

**Comment by Hiswe** [comment]
@Badsender en stage

**Comment by Hiswe** [comment]
@Badsender vous avez pu tester le stage ?

**Comment by Badsender** [comment]
C'est bon! Go pour la prod!

**Comment by Hiswe** [comment]
@Badsender en prod
