### ISSUE TITLE
Bug (?) de déduplication d'élément de contenu

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#34]
Hello,

Je rencontre un problème et suppose que c'est un bug. Voici le détail:

J'ai une série de paramètres au niveau du template (pas dans des blocs donc). Quand je place ces paramètres directement à la racine, pas de soucis, je peux les utiliser:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/39266853/61695286-86eb0f80-ad33-11e9-85ec-e51e9602b16b.png">

Par contre, quand je tente des les grouper, lorsque je clique pour modifier un paramètre, l'affichage se duplique:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/39266853/61695152-45f2fb00-ad33-11e9-8ed5-6352396d7073.png">
Tout fonctionne correctement, au niveau des paramètres, on dirait que c'est vraiment uniquement l'affichage en double de ces paramètres groupés qui bug

Exemple dans:
https://badsender-test.herokuapp.com
Company: tech test
Template: metadata test

Une idée?

**Comment by Hiswe** [comment]
J'ai passé du temps à regarder.
J'ai testé des solutions sur le template pour être sûr qu'il n'y avait pas d'erreurs sur la syntaxe de template et non.
Dès qu'on fait un groupe au niveau de la racine on a ce phénomène de déduplication.

J'ai parcouru les `issues` sur mosaico mais je n'ai rien trouvé de semblable

Prochaine étape : corriger le bug dans l'éditeur !

N.B. Du coup en cherchant tout ça je suis tombé sur le langage de templating développé par Voidlabs :

- [htmml](https://github.com/voidlabs/htmml)
- on peut voir ce que ça donne avec versafix 
  - la partie [htmml](https://github.com/voidlabs/versafix-template/blob/master/template-def/template-versafix-1.htmml)
  - et le [template compilé en html](https://github.com/voidlabs/versafix-template/blob/master/dist/template/template-versafix-1.html)

à voir si ça peut vous servir

**Comment by Hiswe** [comment]
J'ai continué de chercher mais sans plus d'infos… j'arrive pas encore dans le code à différencier un block `root` des autres blocs…

**Comment by Hiswe** [comment]
@Badsender ça devrait être bon sur le serveur de test

https://badsender-test.herokuapp.com/editor/5d6bf4cd73f5920012788b3e

**Comment by Badsender** [comment]
Ça me semble good!
Go pour le stage

**Comment by Hiswe** [comment]
@Badsender en stage

**Comment by Badsender** [comment]
C'est bon pour moi. Go prod!
