### ISSUE TITLE
Bug d'addition

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#35]
Hello,

Un nouveau bug trouvé:
Lorsque j'utilise une addition pour calculer une valeur, comme par exemple
`<td style="height:100px;-ko-height:@[height + 1]px">`
Il se trouve que la valeur initiale calculée est une concaténation (ici, ma valeur initiale vaudra 1001px).
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/39266853/62381155-233ebe80-b54b-11e9-99c2-cf7c760a511c.png">

Dès que je modifie la valeur de la hauteur dans l'interface, l'opération d'addition s'effectue correctement (si je modifie à 150, la valeur de la hauteur sera alors de 150px et de la hauteur + 1 de 151px).
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/39266853/62381183-3782bb80-b54b-11e9-9567-bff77d219940.png">

Le comportement devrait toujours être identique, à savoir une addition.
La variable @height est bien un widget integer.

Exemple disponible dans 
https://badsender-test.herokuapp.com > tech test > addition bug

**Comment by Hiswe** [comment]
@Badsender j'ai poussé un fix.
Ça fonctionnera uniquement pour les `integer`

https://badsender-test.herokuapp.com/editor/5d74d0decb5c5a00123ec051

**Comment by Badsender** [comment]
C'est good.
Go pour le stage !

**Comment by Hiswe** [comment]
@Badsender en stage

**Comment by Badsender** [comment]
OK pour moi!
GO prod
