### ISSUE TITLE
Barre d'édition

### ISSUE THREAD

**Issue by Badsender** [Badsender/mosaico#36]
Hello Yannick,

Pour le moment, nous avons 2 barres d'éditions différentes pour personnaliser certaines parties de texte.
Une complète:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/39266853/63595360-10069800-c5b9-11e9-84f1-434a7a37a9f0.png">

Et une réduite:
<img width="65" alt="image" src="https://user-images.githubusercontent.com/39266853/63595400-24e32b80-c5b9-11e9-9d35-3fc1665c21dd.png">

Serait-il possible d'utiliser la barre complète dans tous les cas?

**Comment by Hiswe** [comment]
@Badsender à priori c'est à régler depuis les templates

**Comment by Badsender** [comment]
Oui et non. Je t'explique ma problématique:
Il est possible de régler ça facilement dans le template en utilisant certains type de balises.
Par exemple, si on rend les balises <td> éditables, nous aurons la barre d'édition large.
Si on rend une balise <p> éditable, on aura la barre d'édition simple.

Auparavant, on rendait presque toujours une balise <td> éditable. Mais depuis quelques temps, pour que les emails soient plus performants au niveau accessibilité, il faut utiliser des balises sémantiquement plus correctes, comme des balises <p>, <h1>, <h2>, …

C'est pour ça qu'il faudrait arriver à mettre en place la barre d'édition large dans tous les cas (ou si compliqué dans tous les cas, ajouter les balises <p>, <h1>, <h2>, <h3>, <h4>)

**Comment by Hiswe** [comment]
@Badsender merci pour l'explication.
Je vais regarder ça, ça devrait pas être trop compliqué :)

**Comment by Hiswe** [comment]
@Badsender en dev

**Comment by Badsender** [comment]
C'est good!
GO pour stage

**Comment by Hiswe** [comment]
@Badsender en stage

**Comment by Badsender** [comment]
C'est bon pour moi en stage. GO pour la prod!
