### ISSUE TITLE
EDITOR – empty inline edit tag disappear

### ISSUE THREAD

**Issue by Hiswe** [Badsender/mosaico#5]
reproduce 

- https://badsender-stage.herokuapp.com/wireframes/593e5d184e8b98000cfd13ff
- create a new email
- empty #pre-header
- unselect block
- reselect block is now impossible

**Comment by Badsender** [comment]
En effet, ça semble résoudre le bug :-). Je valide

**Comment by Badsender** [comment]
Go pour pousser en stage

**Comment by Hiswe** [comment]
@Badsender En stage

**Comment by Badsender** [comment]
@Hiswe Ok! Go pour la prod!
